# Generated by Django 5.0.6 on 2024-05-10 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=225)),
                ('jobs', models.CharField(max_length=225)),
                ('address', models.CharField(max_length=225)),
                ('status', models.CharField(max_length=225)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
